# Regenerates assets/data/us_places.json, the offline place index the onboarding
# location step searches. Run from america_hub/:  python tool/build_us_places.py
import io
import json
import os

STATES = {
    'AL': 'Alabama', 'AK': 'Alaska', 'AZ': 'Arizona', 'AR': 'Arkansas', 'CA': 'California',
    'CO': 'Colorado', 'CT': 'Connecticut', 'DE': 'Delaware', 'DC': 'District of Columbia',
    'FL': 'Florida', 'GA': 'Georgia', 'HI': 'Hawaii', 'ID': 'Idaho', 'IL': 'Illinois',
    'IN': 'Indiana', 'IA': 'Iowa', 'KS': 'Kansas', 'KY': 'Kentucky', 'LA': 'Louisiana',
    'ME': 'Maine', 'MD': 'Maryland', 'MA': 'Massachusetts', 'MI': 'Michigan', 'MN': 'Minnesota',
    'MS': 'Mississippi', 'MO': 'Missouri', 'MT': 'Montana', 'NE': 'Nebraska', 'NV': 'Nevada',
    'NH': 'New Hampshire', 'NJ': 'New Jersey', 'NM': 'New Mexico', 'NY': 'New York',
    'NC': 'North Carolina', 'ND': 'North Dakota', 'OH': 'Ohio', 'OK': 'Oklahoma', 'OR': 'Oregon',
    'PA': 'Pennsylvania', 'PR': 'Puerto Rico', 'RI': 'Rhode Island', 'SC': 'South Carolina',
    'SD': 'South Dakota', 'TN': 'Tennessee', 'TX': 'Texas', 'UT': 'Utah', 'VT': 'Vermont',
    'VA': 'Virginia', 'WA': 'Washington', 'WV': 'West Virginia', 'WI': 'Wisconsin', 'WY': 'Wyoming',
}

# Every incorporated place above roughly 40k residents, plus the neighbourhoods
# and suburbs with an established Turkish community (Paterson, Clifton, Sunnyside,
# Sheepshead Bay, Dearborn, Sunnyvale...) so members recognise their own town.
CITIES = """
AL: Birmingham, Montgomery, Huntsville, Mobile, Tuscaloosa, Hoover, Auburn, Dothan, Madison
AK: Anchorage, Fairbanks, Juneau
AZ: Phoenix, Tucson, Mesa, Chandler, Scottsdale, Glendale, Gilbert, Tempe, Peoria, Surprise, Yuma, Flagstaff, Goodyear, Buckeye, Avondale
AR: Little Rock, Fayetteville, Fort Smith, Springdale, Jonesboro, Rogers, Conway, Bentonville
CA: Los Angeles, San Diego, San Jose, San Francisco, Fresno, Sacramento, Long Beach, Oakland, Bakersfield, Anaheim, Santa Ana, Riverside, Stockton, Irvine, Chula Vista, Fremont, San Bernardino, Modesto, Fontana, Oxnard, Moreno Valley, Huntington Beach, Glendale, Santa Clarita, Garden Grove, Oceanside, Rancho Cucamonga, Santa Rosa, Ontario, Elk Grove, Corona, Lancaster, Palmdale, Salinas, Hayward, Pomona, Escondido, Sunnyvale, Torrance, Pasadena, Orange, Fullerton, Roseville, Visalia, Concord, Thousand Oaks, Simi Valley, Santa Clara, Victorville, Vallejo, Berkeley, El Monte, Downey, Costa Mesa, Inglewood, Carlsbad, Fairfield, West Covina, Murrieta, Richmond, Norwalk, Antioch, Temecula, Burbank, Daly City, Rialto, Santa Maria, El Cajon, San Mateo, Clovis, Compton, Jurupa Valley, Vista, South Gate, Mission Viejo, Vacaville, Carson, Hesperia, Redding, Santa Monica, Westminster, Santa Barbara, Chico, Newport Beach, San Leandro, Whittier, Hawthorne, Citrus Heights, Tracy, Alhambra, Livermore, Buena Park, Menifee, Lakewood, Merced, Hemet, Chino, Indio, Redwood City, Lake Forest, Napa, Tustin, Bellflower, Mountain View, Chino Hills, Baldwin Park, Alameda, Upland, San Ramon, Folsom, Pleasanton, Union City, Perris, Manteca, Lynwood, Apple Valley, Redlands, Turlock, Milpitas, Redondo Beach, Rancho Cordova, Yorba Linda, Palo Alto, Davis, Camarillo, Walnut Creek, Pittsburg, South San Francisco, Yuba City, San Clemente, Laguna Niguel, Pico Rivera, Montebello, Lodi, Madera, Santa Cruz, La Habra, Encinitas, Monterey Park, Tulare, Cupertino, Gardena, National City, Rocklin, Petaluma, Huntington Park, San Rafael, La Mesa, Arcadia, Fountain Valley, Diamond Bar, Woodland, Santee, Lake Elsinore, Porterville, Paramount, Eastvale, Rosemead, Hanford, Highland, Brentwood, Novato, Colton, Cathedral City, Delano, Yucaipa, Watsonville, Placentia, Glendora, Gilroy, Palm Desert, Cerritos, West Sacramento, Aliso Viejo, Poway, La Mirada, Rancho Santa Margarita, Cypress, Dublin, Covina, Azusa, Palm Springs, San Luis Obispo, Ceres, San Jacinto, Lincoln, Newark, Lompoc, El Centro, Danville, Bell Gardens, Coachella, Rancho Palos Verdes, San Bruno, Rohnert Park, Brea, La Puente, Campbell, San Gabriel, Beaumont, Los Banos, Adelanto, Martinez, Culver City, Calexico, Stanton, La Quinta, Monrovia, Barstow, Truckee, Malibu, Beverly Hills, West Hollywood, Manhattan Beach, Hermosa Beach, El Segundo, Sherman Oaks, Studio City, Woodland Hills, Van Nuys, North Hollywood, Encino, Tarzana, Northridge, Chatsworth, Granada Hills, Reseda, Canoga Park, Panorama City, Sylmar, San Pedro, Venice, Silver Lake, Los Feliz, Echo Park, Koreatown, Westwood, Century City, Hollywood
CO: Denver, Colorado Springs, Aurora, Fort Collins, Lakewood, Thornton, Arvada, Westminster, Pueblo, Centennial, Boulder, Greeley, Longmont, Loveland, Broomfield, Castle Rock, Grand Junction, Parker, Littleton, Northglenn, Englewood, Wheat Ridge, Louisville, Golden, Durango, Vail, Aspen, Steamboat Springs
CT: Bridgeport, New Haven, Stamford, Hartford, Waterbury, Norwalk, Danbury, New Britain, West Hartford, Greenwich, Fairfield, Hamden, Bristol, Meriden, Manchester, West Haven, Milford, Stratford, East Hartford, Middletown, Wallingford, Enfield, Shelton, Norwich, Trumbull, Torrington, Glastonbury, Naugatuck, Newington, Cheshire, Vernon, Windsor, New London, Branford, Farmington, Ridgefield, Westport, Darien, New Canaan, Wilton
DE: Wilmington, Dover, Newark, Middletown, Bear, Rehoboth Beach
DC: Washington
FL: Jacksonville, Miami, Tampa, Orlando, St. Petersburg, Port St. Lucie, Cape Coral, Hialeah, Tallahassee, Fort Lauderdale, Pembroke Pines, Hollywood, Gainesville, Miramar, Coral Springs, Palm Bay, West Palm Beach, Lakeland, Clearwater, Pompano Beach, Miami Gardens, Boca Raton, Sunrise, Davie, Deltona, Plantation, Melbourne, Fort Myers, Boynton Beach, Miami Beach, Kissimmee, Homestead, Delray Beach, Daytona Beach, Deerfield Beach, North Miami, Ocala, Sanford, Doral, Sarasota, Bradenton, Wellington, Pensacola, Coral Gables, Bonita Springs, Naples, Weston, Jupiter, Port Orange, Coconut Creek, Ormond Beach, North Port, Winter Garden, Apopka, Titusville, Kendall, Aventura, Key West, Winter Park, Altamonte Springs, Oviedo, Palm Coast, Venice, Fort Pierce, Panama City, Vero Beach, Clermont, Winter Haven, Hallandale Beach, Sunny Isles Beach, Brickell, Wynwood, Little Havana
GA: Atlanta, Augusta, Columbus, Macon, Savannah, Athens, Sandy Springs, Roswell, Johns Creek, Warner Robins, Albany, Alpharetta, Marietta, Valdosta, Smyrna, Dunwoody, Brookhaven, Peachtree Corners, Gainesville, Newnan, Milton, Decatur, Kennesaw, Duluth, Suwanee, Woodstock, Lawrenceville, Buford, Douglasville, Stockbridge, McDonough, Canton, Cumming, Norcross, Tucker, Chamblee, Doraville
HI: Honolulu, Pearl City, Hilo, Kailua, Waipahu, Kaneohe, Kahului, Lahaina
ID: Boise, Meridian, Nampa, Idaho Falls, Pocatello, Caldwell, Coeur d'Alene, Twin Falls, Rexburg, Moscow, Sun Valley
IL: Chicago, Aurora, Joliet, Naperville, Rockford, Elgin, Springfield, Peoria, Champaign, Waukegan, Cicero, Bloomington, Arlington Heights, Evanston, Schaumburg, Bolingbrook, Palatine, Skokie, Des Plaines, Orland Park, Tinley Park, Oak Lawn, Berwyn, Mount Prospect, Normal, Wheaton, Hoffman Estates, Oak Park, Downers Grove, Elmhurst, Glenview, DeKalb, Lombard, Moline, Buffalo Grove, Bartlett, Urbana, Quincy, Crystal Lake, Plainfield, Streamwood, Carol Stream, Romeoville, Rock Island, Hanover Park, Carpentersville, Wheeling, Park Ridge, Addison, Calumet City, Northbrook, Elk Grove Village, Danville, Gurnee, Lake Forest, Highland Park, Evergreen Park, Lincoln Park, Wicker Park, Logan Square, Lakeview, Hyde Park
IN: Indianapolis, Fort Wayne, Evansville, South Bend, Carmel, Fishers, Bloomington, Hammond, Gary, Lafayette, Muncie, Terre Haute, Noblesville, Greenwood, Kokomo, Anderson, Elkhart, West Lafayette, Mishawaka, Portage, Valparaiso, Columbus, Merrillville, Goshen, Michigan City, Zionsville, Westfield
IA: Des Moines, Cedar Rapids, Davenport, Sioux City, Iowa City, Waterloo, Council Bluffs, Ames, West Des Moines, Ankeny, Urbandale, Cedar Falls, Bettendorf, Marion, Dubuque, Clinton
KS: Wichita, Overland Park, Kansas City, Olathe, Topeka, Lawrence, Shawnee, Manhattan, Lenexa, Salina, Hutchinson, Leavenworth, Leawood, Garden City
KY: Louisville, Lexington, Bowling Green, Owensboro, Covington, Richmond, Georgetown, Florence, Elizabethtown, Nicholasville, Hopkinsville, Frankfort, Paducah, Newport
LA: New Orleans, Baton Rouge, Shreveport, Metairie, Lafayette, Lake Charles, Kenner, Bossier City, Monroe, Alexandria, Houma, Slidell
ME: Portland, Lewiston, Bangor, South Portland, Auburn, Biddeford, Augusta, Brunswick, Bar Harbor
MD: Baltimore, Columbia, Germantown, Silver Spring, Waldorf, Frederick, Ellicott City, Glen Burnie, Rockville, Gaithersburg, Bethesda, Dundalk, Bowie, Towson, Aspen Hill, Wheaton, Bel Air, Potomac, Severn, Annapolis, Hagerstown, Salisbury, Laurel, College Park, Greenbelt, Hyattsville, Owings Mills, Pikesville, Catonsville, Odenton, Clarksburg, Olney, Chevy Chase
MA: Boston, Worcester, Springfield, Cambridge, Lowell, Brockton, New Bedford, Quincy, Lynn, Fall River, Newton, Lawrence, Somerville, Framingham, Haverhill, Waltham, Malden, Brookline, Medford, Taunton, Chicopee, Weymouth, Revere, Peabody, Methuen, Barnstable, Pittsfield, Attleboro, Everett, Salem, Westfield, Leominster, Fitchburg, Billerica, Holyoke, Beverly, Marlborough, Woburn, Amherst, Chelsea, Braintree, Natick, Randolph, Watertown, Franklin, Lexington, Needham, Arlington, Andover, Dedham, Wellesley, Belmont, Melrose, Milford, Saugus, Danvers, Gloucester, Northampton, Provincetown, Allston, Brighton, Back Bay, Jamaica Plain, South Boston, Dorchester, Charlestown
MI: Detroit, Grand Rapids, Warren, Sterling Heights, Ann Arbor, Lansing, Dearborn, Clinton Township, Canton, Livonia, Troy, Westland, Farmington Hills, Kalamazoo, Wyoming, Southfield, Rochester Hills, Taylor, Saint Clair Shores, Pontiac, Dearborn Heights, Royal Oak, Novi, Battle Creek, Kentwood, East Lansing, Roseville, Portage, Midland, Muskegon, Lincoln Park, Bay City, Jackson, Holland, Saginaw, Ferndale, Birmingham, Traverse City, Grosse Pointe, Hamtramck, Auburn Hills, Wixom, Northville, Plymouth, Berkley, Madison Heights, Shelby Township, Macomb
MN: Minneapolis, Saint Paul, Rochester, Bloomington, Duluth, Brooklyn Park, Plymouth, Woodbury, Maple Grove, Saint Cloud, Eagan, Eden Prairie, Coon Rapids, Blaine, Burnsville, Lakeville, Minnetonka, Apple Valley, Edina, Saint Louis Park, Moorhead, Mankato, Shakopee, Maplewood, Cottage Grove, Richfield, Roseville, Inver Grove Heights, Andover, Brooklyn Center, Savage, Oakdale, Fridley, Winona, Chaska, Ramsey, Chanhassen, Prior Lake, White Bear Lake, Champlin, Elk River, Faribault, Rosemount, Hastings, Crystal, New Brighton, Golden Valley, Northfield, Stillwater, Hopkins
MS: Jackson, Gulfport, Southaven, Biloxi, Hattiesburg, Olive Branch, Tupelo, Meridian, Starkville, Oxford
MO: Kansas City, Saint Louis, Springfield, Columbia, Independence, Lees Summit, O'Fallon, Saint Joseph, Saint Charles, Blue Springs, Saint Peters, Florissant, Joplin, Chesterfield, Jefferson City, Cape Girardeau, Wildwood, University City, Ballwin, Raytown, Liberty, Wentzville, Kirkwood, Maryland Heights, Gladstone, Grandview, Belton, Webster Groves, Sedalia, Ferguson, Clayton, Branson
MT: Billings, Missoula, Great Falls, Bozeman, Butte, Helena, Kalispell, Whitefish
NE: Omaha, Lincoln, Bellevue, Grand Island, Kearney, Fremont, Hastings, Papillion, Norfolk, La Vista
NV: Las Vegas, Henderson, Reno, North Las Vegas, Sparks, Carson City, Enterprise, Spring Valley, Sunrise Manor, Paradise, Summerlin, Boulder City, Elko, Mesquite
NH: Manchester, Nashua, Concord, Derry, Dover, Rochester, Salem, Merrimack, Londonderry, Hudson, Keene, Portsmouth, Hanover
NJ: Newark, Jersey City, Paterson, Elizabeth, Edison, Woodbridge, Lakewood, Toms River, Hamilton, Trenton, Clifton, Camden, Brick, Cherry Hill, Passaic, Middletown, Union City, Old Bridge, Gloucester Township, East Orange, Bayonne, Franklin, North Bergen, Vineland, Union, Piscataway, New Brunswick, Jackson, Wayne, Irvington, Parsippany, Howell, Perth Amboy, Hoboken, Plainfield, West New York, East Brunswick, Bloomfield, West Orange, Evesham, Bridgewater, South Brunswick, Egg Harbor, Hackensack, Sayreville, Mount Laurel, North Brunswick, Kearny, Linden, Marlboro, Teaneck, Atlantic City, Fort Lee, Fair Lawn, Garfield, Long Branch, Westfield, Princeton, Montclair, Summit, Ridgewood, Englewood, Cliffside Park, Palisades Park, Secaucus, Weehawken, Morristown, Livingston, Millburn, Cranford, Rahway, Scotch Plains, Somerset, Freehold, Manalapan, Marlton, Voorhees, Ocean City, Wildwood, Cape May, Asbury Park, Red Bank, Belleville, Nutley, Rutherford, Lyndhurst, Little Ferry, Ridgefield Park, Bergenfield, Dumont, New Milford, Paramus, Wyckoff, Mahwah, Randolph, Denville, Rockaway, Sparta, Vernon, Newton, Flemington, Hillsborough, Belmar, Point Pleasant, Wall, Neptune, Eatontown, Holmdel, Matawan, Aberdeen, Keyport, Hazlet
NM: Albuquerque, Las Cruces, Rio Rancho, Santa Fe, Roswell, Farmington, Clovis, Hobbs, Alamogordo, Carlsbad, Taos
NY: New York, Buffalo, Yonkers, Rochester, Syracuse, Albany, New Rochelle, Mount Vernon, Schenectady, Utica, White Plains, Hempstead, Troy, Niagara Falls, Binghamton, Freeport, Valley Stream, Long Beach, Rome, North Tonawanda, Ithaca, Poughkeepsie, Jamestown, Elmira, Newburgh, Middletown, Saratoga Springs, Kingston, Peekskill, Watertown, Glen Cove, Lockport, Rye, Beacon, Cohoes, Amsterdam, Oswego, Corning, Plattsburgh, Brooklyn, Queens, Bronx, Staten Island, Manhattan, Astoria, Long Island City, Sunnyside, Woodside, Jackson Heights, Elmhurst, Forest Hills, Rego Park, Flushing, Bayside, Whitestone, College Point, Bushwick, Williamsburg, Greenpoint, Park Slope, Bay Ridge, Sheepshead Bay, Brighton Beach, Coney Island, Sunset Park, Bensonhurst, Borough Park, Crown Heights, Bedford-Stuyvesant, Flatbush, Midwood, Canarsie, Riverdale, Throgs Neck, Harlem, Washington Heights, Upper East Side, Upper West Side, Chelsea, Greenwich Village, East Village, Lower East Side, SoHo, Tribeca, Financial District, Midtown, Murray Hill, Hell's Kitchen, Inwood, Great Neck, Manhasset, Port Washington, Roslyn, Garden City, Mineola, Levittown, Massapequa, Huntington, Smithtown, Commack, Islip, Bay Shore, Patchogue, Riverhead, Southampton, Montauk, Nyack, Nanuet, Spring Valley, Suffern, Monsey, New City, Ossining, Tarrytown, Scarsdale, Harrison, Larchmont, Mamaroneck, Yorktown Heights, Carmel, Fishkill, Wappingers Falls
NC: Charlotte, Raleigh, Greensboro, Durham, Winston-Salem, Fayetteville, Cary, Wilmington, High Point, Concord, Asheville, Greenville, Gastonia, Jacksonville, Chapel Hill, Huntersville, Apex, Burlington, Rocky Mount, Kannapolis, Wake Forest, Mooresville, Hickory, Wilson, Indian Trail, Monroe, Salisbury, Matthews, Sanford, New Bern, Goldsboro, Cornelius, Garner, Morrisville, Holly Springs, Fuquay-Varina, Kernersville, Mint Hill, Statesville, Boone, Davidson
ND: Fargo, Bismarck, Grand Forks, Minot, West Fargo, Williston, Dickinson
OH: Columbus, Cleveland, Cincinnati, Toledo, Akron, Dayton, Parma, Canton, Youngstown, Lorain, Hamilton, Springfield, Kettering, Elyria, Lakewood, Cuyahoga Falls, Middletown, Euclid, Newark, Mansfield, Mentor, Beavercreek, Cleveland Heights, Strongsville, Dublin, Fairfield, Findlay, Warren, Lancaster, Lima, Huber Heights, Westerville, Marion, Grove City, Reynoldsburg, Delaware, Brunswick, Upper Arlington, Stow, North Olmsted, Gahanna, Westlake, North Royalton, Massillon, Medina, Xenia, Athens, Bowling Green, Oxford, Wooster, Solon, Shaker Heights, Rocky River, Avon, Hudson, Twinsburg, Painesville, Sandusky, Zanesville, Chillicothe, Portsmouth, Ashtabula
OK: Oklahoma City, Tulsa, Norman, Broken Arrow, Edmond, Lawton, Moore, Midwest City, Enid, Stillwater, Muskogee, Bartlesville, Owasso, Shawnee, Ardmore, Yukon, Bixby, Jenks
OR: Portland, Salem, Eugene, Gresham, Hillsboro, Beaverton, Bend, Medford, Springfield, Corvallis, Albany, Tigard, Lake Oswego, Keizer, Grants Pass, Oregon City, McMinnville, Redmond, Tualatin, West Linn, Woodburn, Newberg, Forest Grove, Wilsonville, Roseburg, Klamath Falls, Ashland, Astoria, Hood River
PA: Philadelphia, Pittsburgh, Allentown, Erie, Reading, Scranton, Bethlehem, Lancaster, Harrisburg, York, Altoona, Wilkes-Barre, Chester, Williamsport, Easton, Lebanon, Hazleton, New Castle, Johnstown, State College, Norristown, Bensalem, King of Prussia, West Chester, Doylestown, Media, Ardmore, Bryn Mawr, Radnor, Bala Cynwyd, Conshohocken, Levittown, Bristol, Warminster, Horsham, Abington, Cheltenham, Jenkintown, Willow Grove, Chalfont, Quakertown, Pottstown, Phoenixville, Downingtown, Exton, Malvern, Wayne, Villanova, Havertown, Drexel Hill, Upper Darby, Lansdale, Souderton, Perkasie, Sellersville, Emmaus, Nazareth, Stroudsburg, Carlisle, Chambersburg, Hershey, Mechanicsburg, Camp Hill, Indiana, Butler, Cranberry Township, Monroeville, Bethel Park, Mount Lebanon, Greensburg, Uniontown, Beaver Falls, Sharon, Meadville, Bradford, Sunbury, Bloomsburg, Pottsville
PR: San Juan, Bayamon, Carolina, Ponce, Caguas, Guaynabo, Mayaguez, Arecibo
RI: Providence, Warwick, Cranston, Pawtucket, East Providence, Woonsocket, Newport, Central Falls, Westerly, Narragansett, Bristol
SC: Charleston, Columbia, North Charleston, Mount Pleasant, Rock Hill, Greenville, Summerville, Sumter, Goose Creek, Hilton Head Island, Florence, Spartanburg, Myrtle Beach, Aiken, Anderson, Greer, Clemson, Beaufort, Bluffton
SD: Sioux Falls, Rapid City, Aberdeen, Brookings, Watertown, Mitchell, Pierre
TN: Nashville, Memphis, Knoxville, Chattanooga, Clarksville, Murfreesboro, Franklin, Johnson City, Jackson, Hendersonville, Bartlett, Kingsport, Collierville, Smyrna, Cleveland, Brentwood, Germantown, Columbia, Spring Hill, La Vergne, Gallatin, Cookeville, Mount Juliet, Lebanon, Morristown, Oak Ridge, Maryville, Bristol, Sevierville, Gatlinburg
TX: Houston, San Antonio, Dallas, Austin, Fort Worth, El Paso, Arlington, Corpus Christi, Plano, Laredo, Lubbock, Garland, Irving, Amarillo, Grand Prairie, Brownsville, Pasadena, McKinney, Mesquite, McAllen, Killeen, Frisco, Waco, Carrollton, Denton, Midland, Abilene, Beaumont, Round Rock, Odessa, Wichita Falls, Richardson, Lewisville, Tyler, College Station, Pearland, San Angelo, Allen, League City, Sugar Land, Longview, Edinburg, Mission, Bryan, Baytown, Pharr, Temple, Missouri City, Flower Mound, Harlingen, North Richland Hills, Victoria, Conroe, New Braunfels, Mansfield, Cedar Park, Rowlett, Port Arthur, Euless, Georgetown, Pflugerville, DeSoto, San Marcos, Grapevine, Bedford, Galveston, Cedar Hill, Texas City, Wylie, Haltom City, Keller, Coppell, Rockwall, Huntsville, Duncanville, Sherman, The Colony, Burleson, Hurst, Lancaster, Texarkana, Friendswood, Weslaco, Southlake, Kyle, Leander, Little Elm, Prosper, Katy, Spring, The Woodlands, Cypress, Humble, Kingwood, Richmond, Rosenberg, Alvin, Deer Park, La Porte, Channelview, Stafford, Addison, Farmers Branch, University Park, Highland Park, Colleyville, Trophy Club, Roanoke, Argyle, Lake Jackson, Nacogdoches, Lufkin, Del Rio, Eagle Pass, Kerrville, Boerne, Schertz, Cibolo, Universal City, Converse, Selma, Live Oak, Seguin, San Benito, Mercedes, Donna, Alamo, San Juan, Rio Grande City, Brownwood, Big Spring, Plainview, Levelland, Andrews, Pecos, Fort Stockton, Alpine, Marfa
UT: Salt Lake City, West Valley City, Provo, West Jordan, Orem, Sandy, Ogden, St. George, Layton, South Jordan, Lehi, Millcreek, Taylorsville, Logan, Murray, Draper, Bountiful, Riverton, Herriman, Spanish Fork, Roy, Pleasant Grove, Kearns, Tooele, Cottonwood Heights, Springville, Cedar City, Park City, Midvale, American Fork, Kaysville, Holladay, Clearfield, Syracuse, Saratoga Springs, Magna, Washington, South Salt Lake, Farmington, Smithfield, Heber City, Moab
VT: Burlington, South Burlington, Rutland, Essex Junction, Barre, Montpelier, Winooski, Stowe
VA: Virginia Beach, Chesapeake, Arlington, Richmond, Newport News, Alexandria, Hampton, Roanoke, Portsmouth, Suffolk, Lynchburg, Harrisonburg, Charlottesville, Danville, Manassas, Petersburg, Fredericksburg, Winchester, Salem, Herndon, Fairfax, Falls Church, Vienna, Reston, McLean, Tysons, Ashburn, Sterling, Leesburg, Centreville, Chantilly, Springfield, Annandale, Burke, Woodbridge, Dale City, Lorton, Great Falls, Oakton, Gainesville, Haymarket, Bristow, Stafford, Culpeper, Warrenton, Front Royal, Blacksburg, Christiansburg, Radford, Staunton, Waynesboro, Williamsburg, Yorktown, Poquoson, Smithfield, Franklin, Emporia, Martinsville, Wytheville, Abingdon, Bristol
WA: Seattle, Spokane, Tacoma, Vancouver, Bellevue, Kent, Everett, Renton, Federal Way, Yakima, Spokane Valley, Kirkland, Bellingham, Kennewick, Auburn, Pasco, Marysville, Lakewood, Redmond, Shoreline, Richland, Sammamish, Burien, Olympia, Lacey, Edmonds, Puyallup, Bremerton, Bothell, Longview, Issaquah, Wenatchee, Mount Vernon, University Place, Walla Walla, Pullman, Des Moines, SeaTac, Maple Valley, Mercer Island, Bainbridge Island, Kenmore, Camas, Mukilteo, Oak Harbor, Tumwater, Lynnwood, Monroe, Anacortes, Port Angeles, Aberdeen, Ellensburg, Moses Lake, Snoqualmie, Woodinville, Duvall, Gig Harbor, Poulsbo, Silverdale
WV: Charleston, Huntington, Morgantown, Parkersburg, Wheeling, Martinsburg, Fairmont, Beckley, Clarksburg
WI: Milwaukee, Madison, Green Bay, Kenosha, Racine, Appleton, Waukesha, Eau Claire, Oshkosh, Janesville, West Allis, La Crosse, Sheboygan, Wauwatosa, Fond du Lac, New Berlin, Wausau, Brookfield, Beloit, Greenfield, Franklin, Oak Creek, Manitowoc, West Bend, Sun Prairie, Superior, Stevens Point, Neenah, Fitchburg, Muskego, Watertown, De Pere, Mequon, South Milwaukee, Middleton, Menomonee Falls, Menasha, Onalaska, Whitewater, Platteville, Chippewa Falls, Marshfield, Waupun, Baraboo
WY: Cheyenne, Casper, Laramie, Gillette, Rock Springs, Sheridan, Jackson, Cody
"""


def build():
    places = []
    seen = set()
    for line in CITIES.strip().splitlines():
        code, rest = line.split(':', 1)
        code = code.strip()
        assert code in STATES, code
        for city in rest.split(','):
            city = city.strip()
            if not city:
                continue
            key = (city.lower(), code)
            if key in seen:
                continue
            seen.add(key)
            places.append({'city': city, 'state': STATES[code], 'stateCode': code})

    # The state itself is always selectable, so nobody is stranded because their
    # town is missing from the list.
    states = [{'stateCode': c, 'state': n} for c, n in sorted(STATES.items(), key=lambda kv: kv[1])]

    payload = {'version': 1, 'states': states, 'cities': places}
    target = os.path.join('assets', 'data', 'us_places.json')
    os.makedirs(os.path.dirname(target), exist_ok=True)
    with io.open(target, 'w', encoding='utf-8') as handle:
        json.dump(payload, handle, ensure_ascii=False, separators=(',', ':'))
    print('cities: %d  states: %d  bytes: %d' % (len(places), len(states), os.path.getsize(target)))


if __name__ == '__main__':
    build()
