-- Crash reporting, without a third party.
--
-- The console has wanted a "çökmesiz kullanım oranı" card since the operations
-- spec was written, and the usual answer is Sentry or Crashlytics. Both need an
-- account somebody owns, a DSN in the build, and they ship every stack trace
-- our members produce to a server we do not run. The number itself is not hard:
-- it is crashed sessions over sessions. These two tables are that number.
--
-- Retention is thirty days, swept by the ingest route. A crash from March
-- answers no question anybody asks, and stack traces are the one payload here
-- that could carry a member's own words in an error message.

-- One row per app launch. This is the denominator: without it a crash count is
-- a number with no scale - ten crashes is a catastrophe at a hundred launches
-- and noise at a hundred thousand.
CREATE TABLE app_launch_sessions (
  -- Generated by the app, not the server: the crash report that arrives after
  -- the process died has to name the session it belongs to, and it only knows
  -- the id it made itself.
  id UUID PRIMARY KEY,
  -- Nullable on purpose. A crash on the login screen is still a crash, and
  -- refusing to record it would hide exactly the launches that fail earliest.
  member_id UUID,
  platform TEXT NOT NULL CHECK (platform IN ('android', 'ios', 'web', 'other')),
  app_version TEXT NOT NULL,
  os_version TEXT,
  device_model TEXT,
  started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  -- Flipped by the crash ingest. Denormalised so the crash-free rate is one
  -- aggregate over one table rather than a join the dashboard runs every
  -- thirty seconds.
  crashed BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX app_launch_sessions_recent_idx ON app_launch_sessions(started_at DESC);
CREATE INDEX app_launch_sessions_platform_idx ON app_launch_sessions(platform, started_at DESC);

CREATE TABLE app_crash_reports (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  -- No foreign key: the launch row travels over the same network as the crash
  -- and can lose the race or be swept first. A crash that names a session we
  -- never recorded is still worth keeping.
  session_id UUID,
  member_id UUID,
  platform TEXT NOT NULL CHECK (platform IN ('android', 'ios', 'web', 'other')),
  app_version TEXT NOT NULL,
  os_version TEXT,
  device_model TEXT,
  -- Fatal means the member lost the screen. Non-fatal is a handled error the
  -- app recovered from; both are worth counting, only the first ruins a
  -- session.
  fatal BOOLEAN NOT NULL,
  error_type TEXT NOT NULL,
  message TEXT NOT NULL,
  -- Which screen was open. The single most useful field for whoever picks the
  -- bug up, and the cheapest to collect.
  screen TEXT,
  stack TEXT,
  -- Same bug, one row in the console. Without this the top of the list is
  -- twelve copies of one crash from twelve devices and the second-most-common
  -- fault is never seen. Computed in the service, never sent by the client.
  fingerprint TEXT NOT NULL,
  occurred_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX app_crash_reports_recent_idx ON app_crash_reports(occurred_at DESC);
CREATE INDEX app_crash_reports_group_idx ON app_crash_reports(fingerprint, occurred_at DESC);
