'use client';
import { useState } from 'react';

async function send(url: string, payload: Record<string, unknown>) { const response=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)}); const body=await response.json().catch(()=>null); if(!response.ok)throw Error(body?.error?.message??'İşlem tamamlanamadı.'); return body.data; }
export function ContentStudio() {
  const [status,setStatus]=useState<string>(); const [accountId,setAccountId]=useState('');
  async function createAccount(form:FormData){setStatus(undefined);try{const account=await send('/api/content/system-accounts',{displayName:form.get('displayName'),handle:form.get('handle'),reason:form.get('reason')});setAccountId(account.id);setStatus(`${account.displayName} resmî hesabı hazır.`);}catch(e){setStatus(e instanceof Error?e.message:'İşlem tamamlanamadı.');}}
  async function publish(form:FormData){setStatus(undefined);try{const post=await send('/api/content/posts',{authorId:accountId,body:form.get('body'),visibility:form.get('visibility'),regionCode:form.get('regionCode')||undefined,reason:form.get('reason')});setStatus(`Paylaşım yayınlandı: ${post.id}`);}catch(e){setStatus(e instanceof Error?e.message:'İşlem tamamlanamadı.');}}
  const field='mt-1 w-full rounded-lg border border-zinc-700 bg-zinc-950 px-3 py-2 text-sm outline-none focus:border-emerald-400';
  return <div className="grid max-w-5xl gap-6 xl:grid-cols-2"><form action={createAccount} className="rounded-xl border border-white/10 bg-zinc-900/40 p-6"><h2 className="font-semibold">Resmî hesap oluştur</h2><p className="mt-1 text-sm text-zinc-500">Bu hesap giriş yapamaz; yalnızca Gatework üzerinden yayınlar.</p><label className="mt-5 block text-sm">Görünen ad<input className={field} name="displayName" required placeholder="TurkSquare" /></label><label className="mt-4 block text-sm">Handle<input className={field} name="handle" required pattern="[a-z0-9][a-z0-9_-]{2,39}" placeholder="turksquare" /></label><label className="mt-4 block text-sm">İşlem nedeni<textarea className={field} name="reason" required minLength={5} placeholder="Resmî topluluk duyuruları" /></label><button className="mt-5 rounded-lg bg-emerald-400 px-4 py-2 text-sm font-semibold text-zinc-950">Hesabı oluştur</button></form><form action={publish} className="rounded-xl border border-white/10 bg-zinc-900/40 p-6"><h2 className="font-semibold">Akış paylaşımı</h2><p className="mt-1 text-sm text-zinc-500">Yalnızca aktif resmî hesap adına yayınlanır.</p><label className="mt-5 block text-sm">Resmî hesap ID<input className={field} value={accountId} onChange={(e)=>setAccountId(e.target.value)} required placeholder="Önce resmî hesap oluşturun" /></label><label className="mt-4 block text-sm">Metin<textarea className={field} name="body" required minLength={1} maxLength={2200} rows={5} /></label><label className="mt-4 block text-sm">Görünürlük<select className={field} name="visibility"><option value="public">Herkese açık</option><option value="friends_only">Sadece arkadaşlar</option></select></label><label className="mt-4 block text-sm">Eyalet kodu <span className="text-zinc-600">(isteğe bağlı)</span><input className={field} name="regionCode" maxLength={2} placeholder="NY" /></label><label className="mt-4 block text-sm">İşlem nedeni<textarea className={field} name="reason" required minLength={5} /></label><button disabled={!accountId} className="mt-5 rounded-lg bg-emerald-400 px-4 py-2 text-sm font-semibold text-zinc-950 disabled:opacity-40">Paylaşımı yayınla</button></form>{status&&<p className="xl:col-span-2 rounded-lg border border-white/10 bg-zinc-900 p-4 text-sm text-zinc-300">{status}</p>}</div>;
}
